#!/bin/bash

echo "🚂 Complete Railway Setup for SUMO Chatbot"
echo "=========================================="
echo ""
echo "✅ Project created: sumo-chatbot"
echo "✅ Initial deployment started"
echo ""
echo "📝 Next steps to complete setup:"
echo ""

echo "1. Visit your Railway dashboard:"
echo "   https://railway.com/project/b9acaa91-8bb6-4301-ba71-756a49713a11"
echo ""

echo "2. In the Railway dashboard, add these environment variables:"
echo "   - OPENAI_API_KEY = your-api-key-here"
echo "   - OPENAI_MODEL = gpt-3.5-turbo"
echo "   - PORT = 8080"
echo "   - FLASK_ENV = production"
echo "   - CORS_ORIGIN = https://your-vercel-app.vercel.app (or * for testing)"
echo ""

echo "3. Generate a domain for your service:"
echo "   - Click on your service in Railway dashboard"
echo "   - Go to Settings tab"
echo "   - Under 'Domains', click 'Generate Domain'"
echo "   - Copy the generated URL (like https://sumo-chatbot-production.up.railway.app)"
echo ""

echo "4. Update your Vercel frontend:"
echo "   - Go to Vercel dashboard"
echo "   - Update VITE_API_URL with your Railway URL"
echo "   - Redeploy"
echo ""

echo "Alternative CLI commands (run in terminal):"
echo "-------------------------------------------"
echo ""
echo "# Link to the service (choose from list)"
echo "railway service"
echo ""
echo "# Then set variables"
echo 'railway variables --set "OPENAI_API_KEY=sk-..." --set "OPENAI_MODEL=gpt-3.5-turbo" --set "PORT=8080" --set "FLASK_ENV=production" --set "CORS_ORIGIN=https://your-app.vercel.app"'
echo ""
echo "# Check logs"
echo "railway logs"
echo ""
echo "# Generate domain"
echo "railway domain"
echo ""

echo "=========================================="
echo "📌 Your Railway project URL:"
echo "https://railway.com/project/b9acaa91-8bb6-4301-ba71-756a49713a11"
echo ""